### ISSUE TITLE
Get annoying error popup, addon works fine though

### ISSUE THREAD

**Issue by cgcgcgcgcg** [Mr-Kodi/repository.myaccounts#3]
Using Flatpak Kodi on Arch Linux.
![ksnip_20220115-215649](https://user-images.githubusercontent.com/38960370/149636000-3fecfc5b-4226-479a-977b-cc69f5183477.png)

**Comment by Tikipeter** [comment]
Is your PM account still active?

**Comment by cgcgcgcgcg** [comment]
> Is your PM account still active?

Thank you @Tikipeter.
I had both Real Debrid and Premiumize and Premiumize' subscription ended.
I manually removed the PM login from script.module.myaccounts/settings.xml and the error popup was gone.
